## YAML Template.
---
spring:
    application: 
        name: stocks
    data:
        mongodb:
            database: stock_db
            port: 27017
            authentication-database: admin
            username: root
            password: root
server:
    port: 8082
    
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8083/eureka/
        fetch-registry: true
        register-with-eureka: true
